language: go

services:
  - mysql

go:
  - 1.9.x
  - master

sudo: false

before_install:
  - mysql -e "CREATE DATABASE comedian DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci"
  - go get -u github.com/pressly/goose/cmd/goose
  - $HOME/gopath/bin/goose -dir migrations mysql "root@/comedian" up
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls  -service=travis-ci

env:
- DATABASE="root@/comedian?parseTime=true" TZ="Asia/Bishkek" HTTP_BIND_ADDR="0.0.0.0:8080" SUPER_ADMIN_ID="UB9AE7CL9" REPORT_CHANNEL="CBAPFA2J2" REPORT_TIME="18:00" LANGUAGE="en_US" REMINDER_INTERVAL="0" MAX_REMINDERS="0" WARNING_TIME="0" ENABLE_COLLECTOR="true"