version: '2'

services:

  db:
    image: mysql:5.7
    volumes:
      - "database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comedian
      MYSQL_USER: comedian
      MYSQL_PASSWORD: comedian

  comedian:
    image: maddevsio/comedian
    restart: on-failure
    links:
      - db:db
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Bishkek
      DATABASE: comedian:comedian@tcp(db:3306)/comedian?parseTime=true
      HTTP_BIND_ADDR: 0.0.0.0:8080
      SLACK_CLIENT_ID: ${SLACK_CLIENT_ID}
      SLACK_CLIENT_SECRET: ${SLACK_CLIENT_SECRET}
      SLACK_VERIFICATION_TOKEN: ${SLACK_VERIFICATION_TOKEN}

    depends_on:
      - db

volumes:
  database: