userExist = "<@%v> already assigned as standuper in this channel\n"
addUserNoStandupTime = "<@%s> now submits standups in this channel, but there is no standup time set yet!\n"
addUser = "<@%s> assigned to submit standups in this channel\n"
addAdmin = "<@%s> was granted admin access\n"
accessDenied = "This command is not allowed for you! You are not admin\n"

pmExists = "<@%s> was already assigned as PM in this channel"
pmAdded = "<@%s> is assigned as PM in this channel"

deleteUser = "<@%s> no longer submits standups in this channel\n"
deleteAdmin = "<@%s> was removed as admin\n"
listNoStandupers = "No standupers in this channel! To add one, please, use `/comedian_add` slash command"
listNoAdmins = "No admins in this channel! To add one, please, use `/adminadd` slash command"
listStandupers = "Standupers in this channel: %v"
listAdmins = "Admins in this workspace: %v"

addStandupTimeNoUsers = "<!date^%v^Standup time at {time} added, but there is no standup users for this channel|Standup time at 12:00 added, but there is no standup users for this channel>"
addStandupTime = "<!date^%v^Standup time set at {time}|Standup time set at 12:00>"
removeStandupTimeWithUsers = "standup time for this channel removed, but there are people marked as a standuper."
removeStandupTime = "standup time for %s channel deleted" 

showNoStandupTime = "No standup time set for this channel yet! Please, add a standup time using `/standup_time_set` command!"
showStandupTime = "<!date^%v^Standup time is {time}|Standup time set at 12:00>"

wrongNArgs = "Wrong number of arguments"
reportByProjectAndUser = "This user is not set as a standup user in this channel. Please, first add user with `/comedian_add` command"
reportOnProjectHead = "Full Report on project #%s from %v to %v:\n\n"
reportOnProjectCollectorData = "\nTotal commits for period: %v\n"
reportOnUserHead = "Full Report on user <@%s> from %v to %v:\n\n"
reportOnProjectAndUserHead = "Report on user <@%s> in project #%s from %v to %v\n\n"

reportNoData = "No standup data for this period\n"
reportDate = "Report for: %v\n"
reportStandupFromUser = "\nStandup from <@%s>:\n%s\n"
reportIgnoredStandup = "\n<@%s>: ignored standup!\n"
reportShowChannel = "In channel: <#%s>\n"
reportCollectorDataUser = "\nTotal commits for period: %v\nLogged Hours: %v\n\n"
dateError1 = "Starting date is bigger than end date"
dateError2 = "Report end time was in the future, time range was truncated"
userDidNotStandup = "<@%v> did not submit standup!\n"
userDidStandup = "<@%v> submitted standup: "
userDidNotStandupInChannel = "In #%v <@%v> did not submit standup!"
userDidStandupInChannel = "In #%v <@%v> submitted standup: "
PMAssigned = "You have been added as Admin for Comedian"
PMRemoved = "You have been removed as Admin from Comedian"


helloManager = "Hello, Manager!"
standupAccepted = "Good job! Standup accepted! Keep it up!"

p1 = "roblem"
p2 = "ifficul"
p3 = "tuck"
p4 = "uestion"

y1 = "esterday"
y2 = "riday"
y3 = "did"
y4 = "have done"
		
t1 = "oday"
t2 = "going to"
t3 = "plan"

notifyNotAll = "In this channel not all standupers wrote standup today, shame on you: %v."
notifyAllDone = "Congradulations! Everybody wrote their standups today!"
notifyManagerAllDone = "<@%v>, in channel <#%s> all standupers have written standup today"
notifyManagerNotAll = "<@%v>, in channel <#%s> not all standupers wrote standup today, these users ignored standup today: %v."
notifyUsersWarning = "Hey, %v! %v minutes to deadline and the team is still waiting for standups from you!"
notifyDirectMessage = "Hello, <@%s>! You missed the standup deadline in <#%s|%s> channel. Please, write you standup ASAP!"

noWorklogs = "Not enough worklogs: %v hours,"
noCommits = "no commits,"
noStandup = "did not write standup!"

hasWorklogs = "Has enough worklogs: %v hours,"
hasCommits = "commited: %v times,"
hasStandup = "submitted a standup!"

isRook = "<@%v> twiddled in #%v yesterday! (%v)\n"
isRookMonday = "<@%v> twiddled in #%v from Friday till yesterday! (%v)\n"


wrongUsernameError = "Seems like you misspelled username. Please, check and try command again!"

selectUsersToAdd = "Select users to add"
selectUsersToDelete = "Select users to delete"
userDoesNotStandup = "User <@%v> does not standup in this channel\n"
selectUsersToAddAsAdmin = "Select users to add as admin"
noSuchUserInWorkspace = "No such user in your slack!"
userNotAdmin = "This user is not admin!"
wrongProjectName = "Wrong project title!"

DaysDivider = " on "
TimeDivider = " at " 
TimetableNoUsers = "Select standupers to create their timetables"
TimetableCreated = "Timetable for <@%v> created: %v \n"

TimetableUpdated = "Timetable for <@%v> updated: %v \n"
CanNotUpdateTimetable = "Could not update timetable for user <@%v>: %v\n"
NotAStanduper = "Seems like <@%v> is not even assigned as standuper in this channel!\n"
NoTimetableSet = "<@%v> does not have a timetable!\n"
TimetableShow = "Timetable for <@%v> is: %v\n"

CanNotDeleteTimetable = "Could not delete timetable for user <@%v>\n"
TimetableDeleted = "Timetable removed for <@%v>\n"

IndividualStandupersWarning = "Attention <@%s>! %v min before standup deadline! Hurry up!"
IndividualStandupersLate = "<@%v>, you are bad! Submit standup ASAP or I will kill that dog!"
EmptyTimetable = "Timetable is empty"

TimetableShowMonday = "| Monday %02d:%02d "
TimetableShowTuesday = "| Tuesday %02d:%02d "
TimetableShowWednesday = "| Wednesday %02d:%02d "
TimetableShowThursday = "| Thursday %02d:%02d "
TimetableShowFriday = "| Friday %02d:%02d "
TimetableShowSaturday = "| Saturday %02d:%02d "
TimetableShowSunday = "| Sunday %02d:%02d "
ComedianIsNotInChannel = "I do not have this channel in my database... Please, reinvite me if I am already here and try again!"

StandupHandleUserNotAssigned = "I like you, yet, you are not assigned as standuper in this channel, please, contact your PM and try again!"
StandupHandleOneDayOneStandup = "One day = one standup! If you want to update your today standup, just edit the one you already wrote!"
StandupHandleCouldNotSaveStandup = "For some reason i could not save your standup in database. I appologize and ask you to contact your PM."
StandupHandleNoProblemsMentioned = "No problems detected! Make sure you include problems, because I do not believe you have none!"
StandupHandleNoYesterdayWorkMentioned = "Could not get what you did yesterday! Please, describe it more!"
StandupHandleNoTodayPlansMentioned = "Seems like today plans are missing! Please, add them and the team is good to go!"
StandupHandleUpdatedStandup = "Standup edited, Good job!"
StandupHandleCreatedStandup = "Standup saved, well done!"